# Generated by Django 4.1.3 on 2023-10-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bannerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='discription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
