# Generated by Django 4.1.3 on 2023-10-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bannerapp', '0002_alter_bannermodel_discription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannermodel',
            old_name='discription',
            new_name='description',
        ),
    ]
