# Generated by Django 4.1.3 on 2022-12-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproductordermodel',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellproductordermodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sellproductordermodel',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
