# Generated by Django 4.1.3 on 2022-12-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sellingapp', '0002_sellproductordermodel_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproductordermodel',
            name='color',
        ),
    ]
