# Generated by Django 4.1.3 on 2023-01-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0010_productmodel_category'),
        ('Sellingapp', '0004_sellordermodel_country_sellordermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproductordermodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.productmodel'),
        ),
    ]
