# Generated by Django 4.1.3 on 2022-11-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='images',
            field=models.ManyToManyField(to='commonapp.imagemodel'),
        ),
    ]
