# Generated by Django 4.1.3 on 2022-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0002_productmodel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
