# Generated by Django 4.1.3 on 2022-12-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0003_statusmodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='oldfromprice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sellfromprice',
            field=models.FloatField(default=0.0),
        ),
    ]
