# Generated by Django 4.1.3 on 2022-12-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0004_productmodel_oldfromprice_productmodel_sellfromprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='colors',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
