# Generated by Django 4.1.3 on 2023-01-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0010_productmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.CharField(default=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
