# Generated by Django 4.1.3 on 2023-02-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0011_testimonialmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialmodel',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
