# Generated by Django 4.1.3 on 2023-08-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0012_alter_testimonialmodel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='code',
            field=models.CharField(blank=True, default='#1cdb37', max_length=100),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=100),
        ),
    ]
