# Generated by Django 4.1.3 on 2023-08-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0013_alter_statusmodel_code_alter_statusmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
