# Generated by Django 4.1.3 on 2022-12-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchaseapp', '0005_ordermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
