# Generated by Django 4.1.3 on 2022-12-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchaseapp', '0006_reviewmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='postcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
