# Generated by Django 4.1.3 on 2022-12-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchaseapp', '0007_ordermodel_country_ordermodel_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='postcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
