# Generated by Django 4.1.3 on 2023-01-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0010_productmodel_category'),
        ('Purchaseapp', '0008_alter_ordermodel_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproductmodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.statusmodel'),
        ),
        migrations.AlterField(
            model_name='orderedproductmodel',
            name='order_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Purchaseapp.ordermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.statusmodel'),
        ),
    ]
